name=WiFi
version=1.0.0
author=Gigadevice
maintainer=
sentence=Enables the communication with devices that use WiFi.
paragraph=This library is based on the official Arduino WiFi library and adapted to GD32 boards.
category=Communication
url=
architectures=gd32
